name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shared:
    uses: mitlibraries/.github/.github/workflows/ruby-shared-ci.yml@ed81322385810830d3b88f73557e6e1f35ce062a # main
